#!/bin/sh

## info
info() {

    if test "${1}" = ""
    then
        info.all
    else
        info.bottle "${1}"
    fi
}

colour() {
    local m_colour="[38;5;${2}m"
    local reset="[0m"

    printf "${m_colour}${1}${reset}"
}


info.all() {
    printf "%s: %s\n" $(colour "shellar" 163)  "${shellar}"
    printf "%s: %s\n" $(colour "shellar_bin" 111)  "${shellar_bin_path}"
    printf "%s: %s\n" $(colour "shellar_lib" 111)  "${shellar_lib_path}"
    printf "%s: %s\n" $(colour "shellar_bottles" 111) "${shellar_bottles_path}"
    printf "%s: %s\n" $(colour "shellar_themes" 111) "${shellar_themes_path}"

    printf "%s: %s\n" $(colour "custom" 171)  "${shellar_custom}"
    printf "%s: %s\n" $(colour "custom_bottles" 171) "${shellar_custom_bottles_path}"


    printf "%s: " $(colour "bottles" 102)
    IFS=":"
    for p in ${shellar_bottles}
    do
        printf "%s " "${p}"
    done
    printf "\n"

}

info.bottle() {
    local pl="${1}"
    local bottle_dir

    if test -d ${shellar_custom_bottles_path}/${pl}
    then
        bottle_dir=${shellar_custom_bottles_path}/${pl}
    else
        bottle_dir=${shellar_bottles_path}/${pl}
    fi

    if test -d ${bottle_dir}
    then
        printf "plugin %s:\n" ${pl}
    else
        printf "no such plugin %s\n" ${pl}
    fi

    ## functions
    if test -d ${bottle_dir}/funktiot
    then
        printf "functions path: %s" ${bottle_dir}/funktiot
        printf "\n"
    fi

    ## completions
    if test -d ${bottle_dir}/completions
    then
        printf "completions path: %s" ${bottle_dir}/completions
        printf "\n"
    fi

    ## bin
    if test -d ${bottle_dir}/bin
    then
        printf "bin path: %s" ${bottle_dir}/bin
        printf "\n"
    fi

    ## local
    if test -d ${bottle_dir}/local
    then
        printf "local path: %s" ${bottle_dir}/local
        printf "\n"
    fi
}


info "${1}"
